### ISSUE TITLE
Enable AppInsights for Azure deployment

### ISSUE THREAD

**Issue by panesofglass** [c4fsharp/c4fsharp#18]
See https://cockneycoder.wordpress.com/2016/04/08/hosting-suave-in-the-azure-app-service/

**Comment by isaacabraham** [comment]
You might also want to add the client-side metrics capture as well to give you an even richer set of details. I'm planning on doing that at some point on the demonstrator project - when it's done I can give this issue a nudge.

**Comment by panesofglass** [comment]
Done! Thanks!

**Comment by isaacabraham** [comment]
Ok I probably should make a separate repo worth just the core app insights stuff in it etc. I'll do that today.

**Comment by isaacabraham** [comment]
Created a new repo at https://github.com/isaacabraham/azure-fsharp-helpers. The three files in there contain everything you need for: -

1. Binding Azure App Settings into ConfigurationManager.AppSettings.
2. Setting up trace listeners for Azure App Service.
3. AppInsights / Suave integration.

You'll need to make some minor changes to your app for this - I've done the same with the fsharp-demonstrator: -

1. https://github.com/isaacabraham/fsharp-demonstrator/blob/master/src/SuaveHost/Program.fs#L28-L34
2. https://github.com/isaacabraham/fsharp-demonstrator/blob/master/src/SuaveHost/Program.fs#L28-L34
