### ISSUE TITLE
Switch to script-based app / deployment

### ISSUE THREAD

**Issue by panesofglass** [c4fsharp/c4fsharp#2]
Once [WebSharper.Warp uses Suave](https://github.com/intellifactory/websharper.warp/issues/15), switch to script-only mode with [live-reload](https://github.com/tpetricek/suave-xplat-gettingstarted).

**Comment by panesofglass** [comment]
@granicz or @Tarmil, any suggestions on how to get WebSharper.Warp running on Suave within a script file?

@haf or @ademar, any thoughts on whether or not this is a good or bad idea?

**Comment by haf** [comment]
I think we should be using proper executables, generally. Something that captures process signals and such.

**Comment by panesofglass** [comment]
Okay. Should I close this, then?

**Comment by haf** [comment]
I think so, it's not that standard. Others may disagree
